### ISSUE TITLE
Sumo exporter should not send empty log body attributes

### ISSUE THREAD

**Issue by rupeshnemade** [SumoLogic/sumologic-otel-collector#1169]
When we removes body from the logs with filelog receiver and tries to forward it with Sumo exporter then Sumo renders the key value as Nil.
It's expected that if the value is Nil then key should not appear at all.

<img width="867" alt="image" src="https://github.com/SumoLogic/sumologic-otel-collector/assets/31383439/537278dc-35ba-4072-9d3d-b82cbd3801eb">

[This](https://github.com/SumoLogic/sumologic-otel-collector/blob/075d0c5ec6a16d26950aeb641cfd9580f8a9aec7/pkg/exporter/sumologicexporter/sender.go#L402-L408) code logic needs to be updated to not send blank values.

**Comment by swiatekm-sumo** [comment]
Yeah, that looks like a bug. You can work around it by setting the Body to the empty string instead of deleting it.

**Comment by rupeshnemade** [comment]
@swiatekm-sumo Is it possible that because of Nil we are seeing tons of below errors?
`2023-06-21T14:41:29.458Z	warn	ottl@v0.79.0/parser.go:198	failed to execute statement	{"kind": "processor", "name": "transform/flatten", "pipeline": "logs/otlp/containers", "error": "expected pcommon.Map but got string", "statement": "merge_maps(attributes, body, \"insert\")"}`

**Comment by swiatekm-sumo** [comment]
That sounds like an issue in https://github.com/SumoLogic/sumologic-kubernetes-collection. Can you file it there with the configuration you're using?

**Comment by swiatekm-sumo** [comment]
@rupeshnemade can you add a logging processor to your configuration with `verbosity: detailed` and post the otel logs showing your data?

**Comment by rupeshnemade** [comment]
@swiatekm-sumo Attaching the log file
[otel_nil.log](https://github.com/SumoLogic/sumologic-otel-collector/files/11967749/otel_nil.log)

**Comment by swiatekm-sumo** [comment]
This is actually a bug in filelog receiver. The body in your record is actually a nonempty string with the value `<nil>`, and this is what the exporter sends to Sumo. The offending logic is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/edad71083ed070e89b46bd569bb9d8d3abdc4ebd/pkg/stanza/adapter/converter.go#L305C13-L305C13, where the receiver should return a pdata Empty value instead of the string.

Can you file this bug upstream?

**Comment by rupeshnemade** [comment]
I have opened a bug https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24017
