### ISSUE TITLE
stop generating list of modules in CI

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-otel-collector#1190]
List of modules is no longer generated correctly. Please see https://github.com/SumoLogic/sumologic-otel-collector/pull/1188#discussion_r1255511685_

**Comment by c-kruse** [comment]
Well then. Didn't expect this one to go quite so deep. https://github.com/golang/go/issues/61644

**Comment by c-kruse** [comment]
Backing up a bit now that I've been able satisfy my curiosity.

I would be interested to hear how you all find this function valuable @sumo-drosiek, @swiatekm-sumo. I see that we are publishing this as a build asset (and interestingly not as part of our release asset) for FIPS builds. Perhaps we are compelled to provide some sort of SBOM with our fips builds and have fallen short of packaging this alongside our release?

Personally I do not see obvious value in repairing this outside of maybe aiding in the debugging of some unlikely CI issues.
