### ISSUE TITLE
Deprecate `compress_encoding` in sumologic exporter

### ISSUE THREAD

**Issue by swiatekm-sumo** [SumoLogic/sumologic-otel-collector#1199]
`compress_encoding` is used for configuring compression, but this is already done by the `confighttp` helper from core, and works correctly as-is.

We should:
1. Deprecate `compress_encoding` and document using `compression` instead
2. Validate that we only accept `compression` options that Sumo supports
3. Remove `compress_encoding` and all of our own compression code for HTTP

**Comment by rnishtala-sumo** [comment]
@swiatekm-sumo I can close this issue as addresses as part of this [PR](https://github.com/SumoLogic/sumologic-otel-collector/pull/1432) and create a new one for the breaking changes in `v0.94.0`
