### ISSUE TITLE
[k8sprocessor] Owner metadata should have a grace period after deletion

### ISSUE THREAD

**Issue by swiatekm-sumo** [SumoLogic/sumologic-otel-collector#1242]
We keep Pod metadata around after the Pod itself is deleted, to account for telemetry data that might be processed after the deletion takes place. However, we do not do this for owner metadata, whereas we should for the same reason. As is, if a Deployment is deleted and we process data from a Pod belonging to that Deployment afterwards, we won't add the `deployment` attribute.

I believe this was introduced in #710, where we started calculating owner metadata dynamically instead of keeping it alongside Pod metadata.

**Comment by c-kruse** [comment]
@swiatekm-sumo  if you don't mind I'd give this a shot.

Reading through, the most apparent solution would be to reapply that same deferred deletion queue pattern from the pod identity cache to the Owner cache. Probably with some twist to account for the multiple cached collections on that structure. Does that all track?

**Comment by swiatekm-sumo** [comment]
Yeah, I think the same solution will work modulo different types.
