### ISSUE TITLE
Documentation: Resource and Remote Observer Processor links are inverted

### ISSUE THREAD

**Issue by git-johnson** [SumoLogic/sumologic-otel-collector#1251]
When browsing the processors on the `main` branch, I noticed the links to the `resource` processor points to the `remoteobserver` processor in the root `README.md`.
The same is true vice versa.

These links just need to get flipped back around and I would be happy to do it myself.

**Comment by astencel-sumo** [comment]
Indeed! Thanks for the heads-up @git-johnson. We'd be honored to accept your contribution fixing this :smile:

**Comment by git-johnson** [comment]
#1253

**Comment by git-johnson** [comment]
Resolved, thanks @astencel-sumo & @swiatekm-sumo!
