### ISSUE TITLE
OpAMP extension does not log remote config save errors

### ISSUE THREAD

**Issue by portertech** [SumoLogic/sumologic-otel-collector#1356]
The OpAMP extension isn't logging remote configuration save errors.

These errors are currently only surfaced through OpAMP itself:

```
last_remote_config_hash: "1183712915"
  status: RemoteConfigStatuses_FAILED
  error_message: "cannot save the OpAMP effective config to /etc/otelcol-sumo/opamp.d: open /etc/otelcol-sumo/opamp.d/00000000000005AC.yaml: permission denied"
```

Update the extension to log these kinds of errors.

**Comment by rnishtala-sumo** [comment]
fixed this in https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.96.0-sumo-0
