### ISSUE TITLE
Service failure on startup with `otelcol-sumo_0.96.0.0` due to unsupported URI scheme in Windows environment.

### ISSUE THREAD

**Issue by MorbidKoder** [SumoLogic/sumologic-otel-collector#1511]
## Issue Summary
While installing the latest version of the otelcol-sumo service in Windows 10, we've encountered the following issue:

## Error Detail
Encountered error in Windows Event Log:
`failed to start service: unsupported scheme on URI "glob:C:\ProgramData\Sumo Logic\OpenTelemetry Collector\config\conf.d\*.yaml"`

## Reproduction Steps
1. Upgrade to `otelcol-sumo_0.96.0.0`.
2. Attempt service start.
3. Review Windows Event Log for error.

## Temporary Solution
Reverting to `otelcol-sumo_0.94.0.2` eliminates the issue.

![image](https://github.com/SumoLogic/sumologic-otel-collector/assets/1512177/8d33d16e-9feb-4259-9282-e9136f6bf63f)

**Comment by ericSpence** [comment]
I am also seeing this on linux based systems when running a validate.  It does look like the glob command works to start the collector.
`
STEP 18/18: RUN /opt/otel-collector/otelcol-sumo-0.96.0-sumo-1-linux_amd64 --config /opt/otel-collector/config.yaml --config "glob:/opt/otel-collector/conf.d/*" validate
`

`
Error: unsupported scheme on URI "glob:/opt/otel-collector/conf.d/*"
2024/04/04 13:31:49 collector server run finished with error: unsupported scheme on URI "glob:/opt/otel-collector/conf.d/*"
`

`
Error: building at STEP "RUN /opt/otel-collector/otelcol-sumo-0.96.0-sumo-1 --config /opt/otel-collector/config.yaml --config "glob:/opt/otel-collector/conf.d/*" validate": while running runtime: exit status 1
`

**Comment by fguimond** [comment]
This should be fixed as of v0.96.0-sumo-1.
Reference: https://github.com/SumoLogic/sumologic-otel-collector/pull/1512/files

**Comment by swiatekm-sumo** [comment]
@ericSpence the problem you encountered is unrelated, and specific to the `validate` command. It was fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/10203, which will be included in version 0.102.0.
