### ISSUE TITLE
cascadingfilterprocessor should support filtering on trace status

### ISSUE THREAD

**Issue by aclowes** [SumoLogic/sumologic-otel-collector#1573]
The `min_number_of_errors` filter is not useful for accepting traces only when the root span has an error. It would be useful to add a property to the trace like `statuscode` where we can filter to `ERROR`, like in the UI. Thanks.

**Comment by chan-tim-sumo** [comment]
Hi Alec,

Just to make sure, you're talking about filtering the traces by status_code for the root span only right?

**Comment by aclowes** [comment]
> Just to make sure, you're talking about filtering the traces by status_code for the root span only right?

Correct! Thank you.

**Comment by chan-tim-sumo** [comment]
Hey Alec, you can [filter traces by status code for the root span now](https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/processor/cascadingfilterprocessor#just-filtering-out-status-code). Let me know if you have any questions!

**Comment by aclowes** [comment]
Thank you!
