### ISSUE TITLE
opampdreceveiver: refactor unit tests

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-otel-collector#1616]
We should refactor tests, as they have a lot of common code. See the following comment: https://github.com/SumoLogic/sumologic-otel-collector/pull/1614#pullrequestreview-2164984133_

**Comment by rnishtala-sumo** [comment]
PR - https://github.com/SumoLogic/sumologic-otel-collector/pull/1631 , nice work!

cc: @harshshahsumo
