### ISSUE TITLE
[sourceprocessor,sumologicexporter] Remove source templates

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-otel-collector#255]
Source templates are implemented in two places:
 - sourceprocessor (with addidional support for pod_name and possibility to be replaced by pod annotations)
 - sumologicexporter
 
 This is against DRY and to resolve it I propose the following:
 
 - remove source templates from sourceprocessor
 - add ability to define source templates using attribute in sumologicexporter with fallback to current approach
 
 With such solution, sourceprocessor will be able to prepare template based on pod annotations and exporter will take care of rest.

**Comment by aboguszewski-sumo** [comment]
Is the proposed solution still valid or has the idea changed?

**Comment by sumo-drosiek** [comment]
This changed. We are aiming to get rid of source templates in exporter and `_source*` attributes have already special meaning in processor.

This should be removed and only sourceprocessor should modify the data:

```
    # For below described source related configuration,
    # please refer to "Source templates" documentation chapter from this document.

    # desired source category, useful if you want to override the source category
    # configured for the source.
    source_category: <source_category>
    # desired source name, useful if you want to override the source name
    # configured for the source.
    source_name: <source_name>
    # desired host name, useful if you want to override the source host
    # configured for the source.
    source_host: <source_host>
```
