### ISSUE TITLE
[sourceprocessor] add support for `sumologic.com/sourceName` and `sumologic.com/sourceHost` annotations

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-otel-collector#264]
We probably want to add support for [sumologic.com/sourceName][fluent_source_name] and [sumologic.com/sourceHost][fluent_source_host] annotations

[fluent_source_host]: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/v1.12.2-sumo-4/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L194-L196
[fluent_source_name]: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/v1.12.2-sumo-4/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L197-L199

**Comment by astencel-sumo** [comment]
These annotations are already supported, adding documentation for them in #269.
