### ISSUE TITLE
Metadata for pods with specific names is not added

### ISSUE THREAD

**Issue by kkujawa-sumo** [SumoLogic/sumologic-otel-collector#334]
Metadata for pods with specific names is not added by k8sprocessor

For example when pod name is `collection-sumologic-otelcol-logs-1` then some metadata (e.g. `statefulset`) are not available in Sumo.

There is constant list of pod names patterns to ignore, see [this](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/pkg/processor/k8sprocessor/kube/kube.go#L52-L59):

```
	// TODO: move these to config with default values
	podNameIgnorePatterns = []*regexp.Regexp{
		regexp.MustCompile(`jaeger-agent`),
		regexp.MustCompile(`jaeger-collector`),
		regexp.MustCompile(`otel-collector`),
		regexp.MustCompile(`otel-agent`),
		regexp.MustCompile(`collection-sumologic-otelcol`),
	}
```
and `podNameIgnorePatterns` is used in `shouldIgnorePod` see [here](https://github.com/SumoLogic/sumologic-otel-collector/blob/0c2fd59d69b491552ca23fc61d77a138162155e3/pkg/processor/k8sprocessor/kube/client.go#L440-L465).

**Comment by kkujawa-sumo** [comment]
In upstream version of the plugin list of pod names patterns to ignore is configurable https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3520

**Comment by pmalek-sumo** [comment]
rel: https://jira.kumoroku.com/jira/browse/SUMO-179681
