### ISSUE TITLE
Include cumulativetodeltaprocessor from contrib

### ISSUE THREAD

**Issue by EddieEldridge** [SumoLogic/sumologic-otel-collector#595]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor

I would like to use this Processor with the Sumo collector distro. 

I don't see it defined in https://github.com/SumoLogic/sumologic-otel-collector/blob/main/otelcolbuilder/.otelcol-builder.yaml

Is there a reason for this? Or am I misunderstanding something? 

Thanks!

Edit: https://github.com/SumoLogic/sumologic-otel-collector/pull/597

**Comment by kkujawa-sumo** [comment]
Fixed by https://github.com/SumoLogic/sumologic-otel-collector/pull/597
