### ISSUE TITLE
Stability level of sumologic extension is not defined

### ISSUE THREAD

**Issue by calebhailey** [SumoLogic/sumologic-otel-collector#680]
Seeing an error message logged out when starting `otelcol-sumo` version 0.56.0-sumo-0 with info-level logging enabled: 

```
2022-07-27T22:57:32.063Z        info    components/components.go:30     Stability level of component is undefined       {"kind": "exporter", "data_type": "logs", "name": "sumologic", "stability": "undefined"}
```

I suspect we're missing an attribute in our extension to set the stability level. Somehow, seeing "undefined" here is even worse than "alpha" or "experimental". Given that [we've announced the general availability of our OTC distribution](https://www.sumologic.com/press-release/sumo-logic-defines-future-of-agent-collection-on-opentelemetry/) and we are offering commercial support for our distribution (and exporter extension) to our customers, it would be great if we could set this to "beta" or better. 😊 

I got this message on an amd64 linux host running Debian Linux.

**Comment by sumo-drosiek** [comment]
Done in https://github.com/SumoLogic/sumologic-otel-collector/pull/769
