### ISSUE TITLE
need to activate sumologic_schema in common sumologic.yaml otelcol config

### ISSUE THREAD

**Issue by jspaleta** [SumoLogic/sumologic-otel-collector#781]
The otelcol apps repo are making use of the sumologic_schema processor in their app specific configs, but it looks like sumologic_schema isn't activated in the common sumologic.yaml.

Slack discussion indicates the common sumologic.yaml file should be the place where this is activated.

Ref: https://github.com/Sanyaku/apps/issues/25

**Comment by kkujawa-sumo** [comment]
@jspaleta Could you share the link to slack discussion?

**Comment by jspaleta** [comment]
https://sumologic.slack.com/archives/C01KD5GHQ5C/p1666231307341469

**Comment by sumo-drosiek** [comment]
Closing as done in https://github.com/SumoLogic/sumologic-otel-collector/pull/783
