### ISSUE TITLE
Step 3 of the Container Image Installation step should be updated. 

### ISSUE THREAD

**Issue by angadrandhawa1** [SumoLogic/sumologic-otel-collector#790]
The step 3 of [container installation step](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Installation.md#container-image) is a little bit confusing. 

Step 3 - Run the Sumo Logic Distribution for OpenTelemetry collector in container , e.g

When i see this I expect that you are just sharing the example command that I should run. But currently, we are also showing the console output, which was a bit confusing.
If we want to show the console output, we should preempt it with something like
Step 4- When the commands runs successfully you should see a console output similar to
and then show the sample output.

**Comment by astencel-sumo** [comment]
Thanks @angadrandhawa1 for reporting this, here's the proposed fix: https://github.com/SumoLogic/sumologic-otel-collector/pull/791.
