### ISSUE TITLE
Bug: glob config provider doesn't allow for empty config.d directory

### ISSUE THREAD

**Issue by jspaleta** [SumoLogic/sumologic-otel-collector#812]
## Problem Statement
glob config provider doesn't allow for empty config.d director

## Details needed to reproduce 

Using the systemd unit file as provided in examples I noticed that the cmdline invocation:
```
/usr/local/bin/otelcol-sumo --config /etc/otelcol-sumo/sumologic.yaml --config "glob:/etc/otelcol-sumo/conf.d/*.yaml"
```

Doesn't work if the directory `/etc/otelcol-sumo/conf.d/` is empty.
otelcol-sumo service start up will fail with error:

```
Error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: no matching files found for pattern /etc/otelcol-sumo/conf.d/*.yaml
```

The directory does exist, its just empty.. which is the state the collector will be in when using the provided install script.

## Expectated behavior
I would expect that the collector will run with an empty conf.d directory.

## preferred solution
Fix glob provider to allow for empty directory structure

## work-around solution
make sure the install script places a blank yaml file into the conf.d
Sufficient work-around:

```
touch /etc/otelcol-sumo/conf.d/noop.yaml
```

**Comment by swiatekm-sumo** [comment]
The install script puts the user config in there (containing the token at minimum) unless you specifically tell it not to, and in that case the expectation is that you supply your own config files. We could make the glob provider not error if it doesn't find any config files there, but that shouldn't affect typical uses of the install script.

**Comment by jspaleta** [comment]
What I just heard you say was we need to add additional test coverage of the install script for the exposed options to ensure correct operation if a user uses any install option that is not default.

**Comment by jspaleta** [comment]
Is the glob provider intended for upstream submission or is this going to be a sumo distro only feature?  If its intended for upstream, then the assumption that the glob directory will always have at least one file provided by whatever the install process is invalid.

Furthermore, I also find it disturbing in general that a config provider feature would be tightly coupled to an specific installer action being performed. That's not good. If the installer logic changes for whatever reason to no longer provide a file in that directory by default... that complicates a lot.

Looking around at other unix services that use the conf.d pattern on my linux system right now and requiring at least one file in a glob match is an anti-pattern as a default.

Example:
My nginx install uses `include /etc/nginx/conf.d/*.conf;`  in its default config but that directory is not populated by default by the vendor packages.

But the service still runs when I start it with systemd without error and provides me a default proof-of-life webpage.

**Comment by swiatekm-sumo** [comment]
To be clear, I agree that not erroring is correct behaviour if we want to support this kind of configuration structure. My point was that this problem shouldn't affect any users of the install script unless they go out of their way to be exposed to it.

> What I just heard you say was we need to add additional test coverage of the install script for the exposed options to ensure correct operation if a user uses any install option that is not default.

This is covered by tests. What it's not, is documented exhaustively enough.

> Furthermore, I also find it disturbing in general that a config provider feature would be tightly coupled to an specific installer action being performed. That's not good. If the installer logic changes for whatever reason to no longer provide a file in that directory by default... that complicates a lot.

That's not the case. In fact, it's the reverse - the glob provider was added before the install script, and the reason it errors in this case is because the systemd case was not considered at the time. The idea was that starting it with a config option that doesn't output any actual configuration was likely a user error. In the world of systemd services and conf.d directories this is not true, and it's a good reason to change it.
