### ISSUE TITLE
Example configuration doesn't work with latest otelcol build - 'sending_queue' has invalid keys: storage

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-otel-collector#857]
The following [example configuration from the documentation](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/installation.md#verify-the-installation) doesn't work:
```
exporters:
  sumologic:
    sending_queue:
      enabled: true
      storage: file_storage
  logging:

extensions:
  file_storage:
    directory: .
  sumologic:
    collector_name: sumologic-demo
    install_token: ${SUMOLOGIC_INSTALL_TOKEN}

receivers:
  filelog:
    include:
    - /tmp/sumologic-otc-example.log
    include_file_name: false
    include_file_path_resolved: true
    start_at: end

service:
  extensions: [file_storage, sumologic]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [sumologic, logging]
```

Error produced:
```
$ otelcol-sumo --config config.yaml
Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "sumologic": 1 error(s) decoding:

* 'sending_queue' has invalid keys: storage
2022/12/02 13:15:18 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "sumologic": 1 error(s) decoding:

* 'sending_queue' has invalid keys: storage
```

It works for the newest, development otelcol version.

**Comment by perk-sumo** [comment]
I've tested this on both latest release `v0.57.2-sumo-1` and latest dev build `v0.57.2-sumo-0-130-gf1c58e6340` and can confirm I see logs flowing in and no errors in the output.

**Comment by perk-sumo** [comment]
This issue will go away with next release build, so I'm not sure we should act on it now.

**Comment by sumo-drosiek** [comment]
Closing the issue as I confirmed that the example configuration is working: https://github.com/SumoLogic/sumologic-otel-collector/blob/ccdb9b3c6efcb8711fc3eca8ed7791f09b16c727/docs/installation.md#verify-the-installation
