### ISSUE TITLE
Remove remaining data-modifying options from sumologic exporter

### ISSUE THREAD

**Issue by swiatekm-sumo** [SumoLogic/sumologic-otel-collector#875]
Exporters shouldn't modify data, as this messes with fan-out in pipelines and leads to race conditions with multiple exporters. We have a few remaining options in the Sumo exporters that we should either get rid of or move to the sumo schema processor.

- [x] `clear_logs_timestamp` - move to sumo schema processor, or just use transform processor?
- [x] `routing_attribute_to_drop` - drop, routing processor now does this
- [x] `json_logs.add_timestamp` and `json_logs.flatten_body` shouldn't modify the otlp record

**Comment by swiatekm-sumo** [comment]
See https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2933 for examples on how these features can be reproduced using the transform processor.

**Comment by echlebek** [comment]
@swiatekm-sumo necessary to reproduce these features elsewhere before removal? Are there other issues filed for this?

**Comment by echlebek** [comment]
Thanks, it seems pretty straightforward!

**Comment by sumo-drosiek** [comment]
https://github.com/SumoLogic/sumologic-otel-collector/pull/1201
https://github.com/SumoLogic/sumologic-otel-collector/pull/1372 
https://github.com/SumoLogic/sumologic-otel-collector/pull/1371

**Comment by swiatekm-sumo** [comment]
#1373 and #1378 should be closed before we close this issue.
