### ISSUE TITLE
Remove workaround replace statements for components using otelcoltest

### ISSUE THREAD

**Issue by swiatekm-sumo** [SumoLogic/sumologic-otel-collector#894]
See https://github.com/SumoLogic/sumologic-otel-collector/pull/891 for a description. This should be fixed by 0.70.0, and the replace statements can then be removed.

**Comment by sumo-drosiek** [comment]
@swiatekm-sumo  Is it done?

**Comment by swiatekm-sumo** [comment]
Nope, I'll update the milestone to v0.71.0
